name: ci

on:
  push:
    branches: [main]
    # 특정 디렉터리 제한
    paths:
      - 'apps/punk-record/**'
      - 'apps/web/**'
      - 'apps/docs/**'
    # 태그로 제한
    tags:
      - 'build-*'

jobs:
  build_packages:
    runs-on: ubuntu-latest
    needs: build_packages
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      # git diff로 변경사항 체크해서 환경 변수에 추가, 근데 이렇게하면 steps 마다 if문 걸어줘야함..
      - name: Check for changes in 'apps/punk-record'
        id: changes_detected
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q '^apps/punk-record/'; then
            echo "changes=true" >> $GITHUB_ENV
          else
            echo "No changes in 'apps/punk-record'"
            echo "changes=false" >> $GITHUB_ENV
          fi

      - name: Install dependencies.
        if: steps.changes_detected.outputs.changes == 'true'
