name: ci

on:
  push:
    branches: [main]

env:
  NODE_VERSION: '20.12.1'
  PNPM_VERSION: '8.15.6'

jobs:
  build_packages:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install PNPM
        run: npm install -g pnpm@${{ env.PNPM_VERSION }}

      - name: Cache PNPM Store
        id: pnpm-cache
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm run build --filter @repo/**

  build-punk-repo:
    runs-on: ubuntu-latest
    needs: build_packages
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Check for changes in 'apps/punk-record'
        id: changes_detected
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q '^apps/punk-record/'; then
            echo "changes=true" >> $GITHUB_ENV
            echo "::set-output name=changes::true"
          else
            echo "No changes in 'apps/punk-record'"
            echo "changes=false" >> $GITHUB_ENV
            echo "::set-output name=changes::false"
          fi

      - name: Set up Node.js
        if: steps.changes_detected.outputs.changes == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies.
        if: steps.changes_detected.outputs.changes == 'true'
        run: |
          pwd
          touch .env
          echo BACK_SERVER_BASE_URL=${{ secrets.BACK_SERVER_BASE_URL }} >> .env
          echo FRONT_SERVER_BASE_URL=${{ secrets.FRONT_SERVER_BASE_URL }} >> .env
          echo PORT=${{ secrets.PORT }} >> .env
          cat .env

      - name: Install PNPM
        if: steps.changes_detected.outputs.changes == 'true'
        run: npm install -g pnpm@${{ env.PNPM_VERSION }}

      - name: Install dependencies
        if: steps.changes_detected.outputs.changes == 'true'
        run: pnpm install

      - name: Build Punk Record App
        if: steps.changes_detected.outputs.changes == 'true'
        run: pnpm run build --filter @app/punk-record

      - name: Compress the built code.
        if: steps.changes_detected.outputs.changes == 'true'
        run: zio -r build.zip ./*.json ./*.yaml ./apps/punk-record/.next ./apps/punk-record/public ./apps/punk-record/*.json ./apps/punk-record/*.yaml

      - name: Install sshpass
        if: steps.changes_detected.outputs.changes == 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Copy files to the personal server via SCP.
        if: steps.changes_detected.outputs.changes == 'true'
        env:
          SSHPASS: ${{ secrets.SERVER_PASSWORD }}
        run: |
          sshpass -e scp -o StrictHostKeyChecking=no build.zip ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }}:${{ secrets.DEPLOY_PATH }}

      - name: Deploy on the server.
        if: steps.changes_detected.outputs.changes == 'true'
        env:
          SSHPASS: ${{ secrets.SERVER_PASSWORD }}
        run: |
          sshpass -e ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} <<'ENDSSH'
          echo "START DEPLOY"
          cd ${{ secrets.DEPLOY_PATH }}
          echo "Current directory:"
          pwd
          echo "Unzipping build.zip"
          unzip -o build.zip
          echo "Unzip completed"
          echo "Restarting application"
          npx pm2 start ./apps/punk-record/ecosystem.config.js
          echo "Deployment completed"
          ENDSSH
